import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, signInAnonymously, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getDatabase, ref, set, update, get, onValue, onDisconnect, remove } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js';
import { firebaseConfig } from './firebase-config.js';

const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getDatabase(app); let uid=null,roomId=null,roomUnsub=null,selectedGame='tictactoe',state=null;
const $=id=>document.getElementById(id), screens=['home','lobby','game']; const games={
 tictactoe:['❌⭕','Tic-Tac-Toe','Classic 3 × 3'],connect4:['🔴🟡','Connect 4','Get four in a row'],rps:['✊✋✌️','Rock Paper Scissors','Best of 5'],
 spy:['🕵️','Spy vs Spy','Hide, scan & trap'],battle:['⚔️','Mini Battle Arena','Move & attack'],battleship:['🚢','Battleship','Sink the fleet'],quiz:['🧠','Quiz Duel','Fast answers win'],race:['🏎️','2D Racing','Reach the finish'],archery:['🏹','Bow & Arrow Duel','Aim & fire'],bomb:['💣','Bomb Arena','Trap your opponent'],word:['🔤','Word Battle','Build the best word'],castle:['🏰','Castle Defense','Protect your castle'],number:['🔢','Hidden Number','Guess the secret']
};
function show(s){screens.forEach(x=>$(x).classList.toggle('active',x===s))} function name(){return ($('nameInput').value.trim()||'Player').slice(0,16)} function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)} function status(el,msg,error=false){$(el).textContent=msg;$(el).classList.toggle('error',error)} function code(){return Math.random().toString(36).slice(2,8).toUpperCase()} function other(me){return me===1?2:1} function players(r){return r.players||{}} function me(r){return players(r)[uid]?.number||0} function save(data){
  // Render the move locally immediately, then sync it to Firebase.
  // This removes UI lag on slower mobile connections while the realtime
  // listener continues to keep both players synchronized.
  if(data?.state && state){
    state={...state,state:data.state};
    renderGame(state);
  }
  return update(ref(db,'rooms/'+roomId),data);
}
const Q=[['What is the SI unit of force?',['Joule','Newton','Watt','Pascal'],1],['Which planet is known as the Red Planet?',['Venus','Mars','Jupiter','Mercury'],1],['2 + 2 × 3 = ?',['12','8','10','6'],1],['Which ocean is the largest?',['Atlantic','Indian','Pacific','Arctic'],2],['HTML is mainly used to…',['Style pages','Structure pages','Query databases','Compile code'],1],['Which gas do plants use in photosynthesis?',['Oxygen','Nitrogen','Carbon dioxide','Hydrogen'],2],['What is the square root of 144?',['10','11','12','14'],2],['Which is a prime number?',['21','27','29','33'],2]];
function fresh(g){
 const base={game:g,turn:1,winner:0,draw:false,score:{1:0,2:0}};
 if(g==='connect4')return {...base,board:Array(42).fill(0)}; if(g==='rps')return {...base,choices:{1:'',2:''},round:1}; if(g==='tictactoe')return {...base,board:Array(9).fill('')};
 if(g==='spy')return {...base,round:1,choices:{1:null,2:null},winner:0}; if(g==='battle')return {...base,hp:{1:5,2:5},pos:{1:{x:0,y:0},2:{x:4,y:4}},round:1};
 if(g==='battleship')return {...base,ships:{1:[9,10,11,12,17,25,33,41,49,57,58,59,60],2:[2,10,18,26,34,42,43,44,45,53,54,55,56]},hits:{1:[],2:[]},shots:{1:[],2:[]},boardSize:8};
 if(g==='quiz')return {...base,q:0,answers:{1:null,2:null},scores:{1:0,2:0},finished:false}; if(g==='race')return {...base,pos:{1:0,2:0},boost:{1:0,2:0},finished:false};
 if(g==='archery')return {...base,shots:{1:[],2:[]},round:1}; if(g==='bomb')return {...base,players:{1:{x:0,y:0,hp:3},2:{x:4,y:4,hp:3}},bombs:[],turn:1};
 if(g==='word')return {...base,round:1,letters:{1:'',2:''},scores:{1:0,2:0},letter:String.fromCharCode(65+Math.floor(Math.random()*26))};
 if(g==='castle')return {...base,hp:{1:10,2:10},resources:{1:3,2:3},turn:1,round:1}; if(g==='number')return {...base,secret:Math.floor(Math.random()*91)+10,guesses:{1:[],2:[]},last:null,finished:false};
 return base;
}
function initGrid(){ $('gameGrid').innerHTML=Object.entries(games).map(([id,g])=>`<button class="game-card ${id===selectedGame?'selected':''}" data-game="${id}"><span>${g[0]}</span><b>${g[1]}</b><small>${g[2]}</small></button>`).join('');$('gameCount').textContent=`· ${Object.keys(games).length}`;document.querySelectorAll('.game-card').forEach(b=>b.onclick=()=>{selectedGame=b.dataset.game;document.querySelectorAll('.game-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')})}
function subscribe(){if(roomUnsub)roomUnsub();roomUnsub=onValue(ref(db,'rooms/'+roomId),s=>{state=s.val();if(!state){leaveLocal();return}renderRoom(state)});onDisconnect(ref(db,`rooms/${roomId}/players/${uid}/online`)).set(false)}
async function createRoom(){if(!uid)return status('homeStatus','Connecting…',true);roomId=code();const room={createdAt:Date.now(),game:selectedGame,players:{[uid]:{number:1,name:name(),online:true}},state:fresh(selectedGame)};try{await set(ref(db,'rooms/'+roomId),room);subscribe();show('lobby');renderRoom(room)}catch(e){roomId=null;console.error('Create room error:',e);status('homeStatus',`Could not create room: ${e.code||e.message||'Firebase error'}`,true)}}
async function joinRoom(){const id=$('roomInput').value.trim().toUpperCase();if(id.length!==6)return status('homeStatus','Enter a 6-character room code.',true);try{const s=await get(ref(db,'rooms/'+id));if(!s.exists())return status('homeStatus','Room not found.',true);const r=s.val();if(Object.keys(players(r)).length>=2&&!players(r)[uid])return status('homeStatus','Room is full.',true);roomId=id;const nums=Object.values(players(r)).map(p=>p.number),n=nums.includes(1)?2:1;await update(ref(db,`rooms/${id}/players/${uid}`),{number:n,name:name(),online:true});subscribe();show('lobby')}catch(e){console.error('Join room error:',e);status('homeStatus',`Could not join room: ${e.code||e.message||'Firebase error'}`,true)}}
function renderRoom(r){const ps=players(r),list=Object.values(ps).sort((a,b)=>a.number-b.number);$('roomCode').textContent=roomId;$('p1Name').textContent=list.find(p=>p.number===1)?.name||'Player 1';$('p2Name').textContent=list.find(p=>p.number===2)?.name||'Waiting…';$('p2Online').className=list.find(p=>p.number===2)?.online?'online':'waiting';if(list.length>=2){status('lobbyStatus','Both players are ready!');show('game');renderGame(r)}}
function checkTTT(b){for(const [a,c,d] of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a]==='X'?1:2;return b.every(Boolean)?-1:0} function checkC4(b){for(let r=0;r<6;r++)for(let c=0;c<7;c++){let x=b[r*7+c];if(!x)continue;for(const[dr,dc]of[[0,1],[1,0],[1,1],[1,-1]]){let ok=true;for(let k=1;k<4;k++){let rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=6||cc<0||cc>=7||b[rr*7+cc]!==x)ok=false}if(ok)return x}}return b.every(Boolean)?-1:0}
function renderGame(r){const g=r.state||fresh(r.game),m=me(r),ps=players(r),by=n=>Object.values(ps).find(p=>p.number===n);$('gameRoomCode').textContent=roomId;$('gameP1').textContent=by(1)?.name||'Player 1';$('gameP2').textContent=by(2)?.name||'Player 2';$('score1').textContent=g.scores?.[1]??g.score?.[1]??0;$('score2').textContent=g.scores?.[2]??g.score?.[2]??0;$('gameIcon').textContent=games[g.game]?.[0]||'🎮';$('gameName').textContent=games[g.game]?.[1]||g.game;const fn=RENDER[g.game]||renderGeneric;fn(g,m,r)}
function setBoard(html,cls='board'){ $('board').className=cls;$('board').innerHTML=html }
const RENDER={
 tictactoe:(g,m)=>{setBoard(g.board.map((v,i)=>`<button class="cell" data-i="${i}" ${v||g.turn!==m||g.winner?'disabled':''}>${v}</button>`).join(''),'board ttt');$('board').querySelectorAll('.cell').forEach(b=>b.onclick=()=>ttt(+b.dataset.i));turn(g,m)},
 connect4:(g,m)=>{setBoard(g.board.map((v,i)=>`<button class="cell ${v===1?'p1':v===2?'p2':''}" data-i="${i}" ${g.turn!==m||g.winner?'disabled':''}></button>`).join(''),'board connect');$('board').querySelectorAll('.cell').forEach(b=>b.onclick=()=>c4(+b.dataset.i%7));turn(g,m)},
 rps:(g,m)=>{setBoard(['✊','✋','✌️'].map((x,i)=>`<button class="choice" data-c="${['rock','paper','scissors'][i]}" ${g.winner?'disabled':''}>${x}<small>${['Rock','Paper','Scissors'][i]}</small></button>`).join(''),'board rps');$('board').querySelectorAll('.choice').forEach(b=>b.onclick=()=>rps(b.dataset.c));$('turnStatus').textContent=g.winner?(g.winner===-1?'Round draw':g.winner===m?'You won!':'Opponent won!'):(g.choices?.[m]?'Waiting…':'Choose your move');status('gameStatus',g.winner?'Round over — Restart for next round.':'Pick rock, paper or scissors.')},
 spy:(g,m)=>{const opts=['🕶️ Sneak','📡 Scan','💣 Trap'];setBoard(opts.map((x,i)=>`<button class="choice" data-i="${i}">${x}</button>`).join(''),'board choices');$('board').querySelectorAll('.choice').forEach(b=>b.onclick=()=>spyMove(+b.dataset.i));$('turnStatus').textContent=g.winner?'Round over':g.choices?.[m]!=null?'Waiting for opponent…':'Choose a secret action';status('gameStatus',g.winner?(g.winner===m?'You win!':'Opponent wins!'):'Both actions are revealed only after both choose.')},
 battle:(g,m)=>{const p=g.pos[m],opp=g.pos[other(m)];let cells='';for(let y=0;y<5;y++)for(let x=0;x<5;x++){let here=p.x===x&&p.y===y?'🤺':opp.x===x&&opp.y===y?'👾':'';cells+=`<button class="cell arena" data-x="${x}" data-y="${y}">${here}</button>`}setBoard(cells,'board arena-grid');$('board').querySelectorAll('.arena').forEach(b=>b.onclick=()=>battleMove(+b.dataset.x,+b.dataset.y));turn(g,m);status('gameStatus',`Your HP ${g.hp[m]} · Opponent HP ${g.hp[other(m)]}. Move to an adjacent tile; land on opponent to attack.`)},
 battleship:(g,m)=>{const o=other(m),size=g.boardSize||8,own=g.ships[m]||[],enemyShots=g.shots[m]||[],myHits=g.hits[m]||[],enemyHits=g.hits[o]||[];const target=Array.from({length:size*size},(_,i)=>{const hit=enemyHits.includes(i),shot=enemyShots.includes(i);return `<button class=\"bs-cell ${hit?'bs-hit':''} ${shot&&!hit?'bs-miss':''}\" data-i=\"${i}\" ${g.winner||shot||g.turn!==m?'disabled':''}>${hit?'💥':shot?'•':''}</button>`}).join('');const ownGrid=Array.from({length:size*size},(_,i)=>{const ship=own.includes(i),hit=myHits.includes(i);return `<div class=\"bs-cell own ${ship?'bs-ship':''} ${hit?'bs-hit':''}\">${hit?'💥':ship?'▰':''}</div>`}).join('');setBoard(`<div class=\"battle-wrap\"><div class=\"fleet-panel\"><div class=\"fleet-top\"><div><span class=\"fleet-kicker\">ENEMY WATERS</span><h3>Target Grid</h3></div><span class=\"radar\">◉ LIVE</span></div><div class=\"bs-grid target-grid\">${target}</div><div class=\"legend\"><span><i class=\"dot hit-dot\"></i> Hit</span><span><i class=\"dot miss-dot\"></i> Miss</span><span>Tap a tile to fire</span></div></div><div class=\"fleet-panel own-panel\"><div class=\"fleet-top\"><div><span class=\"fleet-kicker\">YOUR FLEET</span><h3>Fleet Status</h3></div><span class=\"ships-left\">${own.filter(i=>!myHits.includes(i)).length} hull tiles</span></div><div class=\"bs-grid own-grid\">${ownGrid}</div><div class=\"legend\"><span>▰ Your ship</span><span>💥 Damaged</span></div></div></div>`, 'board battleship-board');$('board').querySelectorAll('.bs-cell:not(.own)').forEach(b=>b.onclick=()=>{b.classList.add('bs-fire');setTimeout(()=>shipShot(+b.dataset.i),120)});$('turnStatus').textContent=g.winner?(g.winner===m?'FLEET VICTORY':'FLEET DEFEATED'):g.turn===m?'🔥 YOUR TURN — FIRE!':'⏳ ENEMY TURN';status('gameStatus',g.winner?(g.winner===m?'You sank the enemy fleet!':'Your fleet has been sunk.'):g.turn===m?'Choose a target in Enemy Waters.':'Waiting for the opponent to fire…')},
 quiz:(g,m)=>{if(g.finished){setBoard(`<div class="result"><h2>Quiz complete!</h2><p>You: ${g.scores[m]} · Opponent: ${g.scores[other(m)]}</p><button class="primary" id="quizRestart">Play again</button></div>`);$('quizRestart').onclick=restart;return}const q=Q[g.q];setBoard(`<div class="quiz-card"><p class="muted">Question ${g.q+1}/${Q.length}</p><h2>${q[0]}</h2><div class="answer-grid">${q[1].map((a,i)=>`<button class="choice" data-i="${i}" ${g.answers[m]!=null?'disabled':''}>${a}</button>`).join('')}</div></div>`);$('board').querySelectorAll('.choice').forEach(b=>b.onclick=()=>quiz(+b.dataset.i));$('turnStatus').textContent=g.answers[m]!=null?'Waiting for opponent…':'Answer fast';status('gameStatus',g.answers[other(m)]!=null?'Opponent answered.':'Both answers are revealed when both submit.')},
 race:(g,m)=>{setBoard(`<div class="race"><div class="track"><span>🏁</span><div class="runner" style="width:${g.pos[1]}%">🧑</div></div><div class="track"><span>🏁</span><div class="runner" style="width:${g.pos[2]}%">🤖</div></div><div class="race-actions"><button class="primary" id="raceGo">GO +${10+Math.floor(Math.random()*8)}%</button><button class="secondary" id="raceBoost">BOOST</button></div></div>`);$('raceGo').onclick=()=>raceMove(false);$('raceBoost').onclick=()=>raceMove(true);$('turnStatus').textContent=g.finished?(g.winner===m?'You won!':'Opponent won!'):'Tap GO';status('gameStatus','First player to reach 100% wins. Boost is a limited +25%.')},
 archery:(g,m)=>{setBoard(`<div class="archery"><div class="target">🎯</div><div class="angle-row">${[20,35,50,65,80].map(a=>`<button class="choice angle" data-a="${a}">${a}°</button>`).join('')}</div><p>Choose an angle. Wind is hidden until both fire.</p></div>`);$('board').querySelectorAll('.angle').forEach(b=>b.onclick=()=>archery(+b.dataset.a));$('turnStatus').textContent=g.shots[m]?.length?'Waiting…':'Choose angle';status('gameStatus',`Round ${g.round}/5 · Highest accuracy wins the round.`)},
 bomb:(g,m)=>{const p=g.players[m];let cells='';for(let y=0;y<5;y++)for(let x=0;x<5;x++){const bomb=g.bombs.find(b=>b.x===x&&b.y===y);let icon=p.x===x&&p.y===y?'🧑':g.players[other(m)].x===x&&g.players[other(m)].y===y?'👾':bomb?'💣':'';cells+=`<button class="cell arena" data-x="${x}" data-y="${y}">${icon}</button>`}setBoard(cells,'board arena-grid');$('board').querySelectorAll('.arena').forEach(b=>b.onclick=()=>bombMove(+b.dataset.x,+b.dataset.y));turn(g,m);status('gameStatus',`HP ${p.hp} · Move one square. You can place a bomb on your current square.`)},
 word:(g,m)=>{setBoard(`<div class="word-card"><div class="letter">${g.letter}</div><p>Make a word beginning with this letter.</p><input id="wordInput" maxlength="12" placeholder="Your word" ${g.letters[m]?'disabled':''}><button class="primary" id="wordSubmit">Submit</button><div class="word-info">Round ${g.round}/5 · Your score ${g.scores[m]}</div></div>`);$('wordSubmit').onclick=()=>wordMove($('wordInput').value);$('turnStatus').textContent=g.letters[m]?'Waiting…':'Your turn';status('gameStatus',g.letters[other(m)]?'Opponent submitted.':'Valid word = points; longer word scores more.')},
 castle:(g,m)=>{setBoard(`<div class="castle"><div class="castles"><div>🏰<b>${g.hp[1]}</b><small>P1 Castle</small></div><div>🏰<b>${g.hp[2]}</b><small>P2 Castle</small></div></div><div class="castle-actions"><button class="choice" data-a="attack">⚔️ Attack</button><button class="choice" data-a="repair">🛠️ Repair</button><button class="choice" data-a="charge">💰 Charge</button></div><p>Attack costs 1 resource and deals 2 damage. Repair restores 1 HP. Charge gains 1 resource.</p></div>`);$('board').querySelectorAll('.choice').forEach(b=>b.onclick=()=>castleMove(b.dataset.a));turn(g,m);status('gameStatus',`Your resources: ${g.resources[m]}. Reduce the enemy castle to 0.`)},
 number:(g,m)=>{setBoard(`<div class="number-card"><p>Guess a number from <b>10–100</b>.</p><div class="number-input"><input id="guess" type="number" min="10" max="100" placeholder="50"><button class="primary" id="guessBtn">Guess</button></div><div class="guesses">${(g.guesses[m]||[]).slice(-5).map(x=>`<span>${x}</span>`).join('')}</div></div>`);$('guessBtn').onclick=()=>numberMove(+$('guess').value);$('turnStatus').textContent=g.finished?(g.winner===m?'You guessed it!':'Opponent guessed it!'):'Guessing';status('gameStatus',g.last?`Last result: ${g.last}`:'Higher or lower — first exact guess wins.')}
};
function turn(g,m){$('turnStatus').textContent=g.winner?(g.winner===-1?'Draw':g.winner===m?'You won!':'Opponent won!'):g.turn===m?'Your turn':'Opponent’s turn'}
async function ttt(i){const g=state.state,m=me(state);if(g.turn!==m||g.board[i]||g.winner)return;const b=[...g.board];b[i]=m===1?'X':'O';const w=checkTTT(b),s={...g.score};if(w>0)s[w]++;await save({state:{...g,board:b,winner:w,draw:w===-1,score:s,turn:w?g.turn:other(m)}})}
async function c4(col){const g=state.state,m=me(state);if(g.turn!==m||g.winner)return;const b=[...g.board];let row=-1;for(let r=5;r>=0;r--)if(!b[r*7+col]){row=r;break}if(row<0)return;b[row*7+col]=m;const w=checkC4(b),s={...g.score};if(w>0)s[w]++;await save({state:{...g,board:b,winner:w,score:s,turn:w?g.turn:other(m)}})}
async function rps(c){const g=state.state,m=me(state);if(g.winner||g.choices[m])return;const ch={...g.choices,[m]:c};let w=0;if(ch[1]&&ch[2]){w=ch[1]===ch[2]?-1:((ch[1]==='rock'&&ch[2]==='scissors')||(ch[1]==='paper'&&ch[2]==='rock')||(ch[1]==='scissors'&&ch[2]==='paper'))?1:2}const s={...g.score};if(w>0)s[w]++;await save({state:{...g,choices:ch,winner:w,score:s,turn:w?g.turn:other(m)}})}
async function spyMove(a){const g=state.state,m=me(state);if(g.winner||g.choices[m]!=null)return;const c={...g.choices,[m]:a};if(c[1]==null||c[2]==null)return save({state:{...g,choices:c}});let w=0;if(c[1]===c[2])w=-1;else if((c[1]===0&&c[2]===2)||(c[1]===1&&c[2]===0)||(c[1]===2&&c[2]===1))w=1;else w=2;const s={...g.score};if(w>0)s[w]++;await save({state:{...g,choices:c,winner:w,score:s}})}
async function battleMove(x,y){const g=state.state,m=me(state),o=other(m),p=g.pos[m];if(g.winner||g.turn!==m||Math.abs(x-p.x)+Math.abs(y-p.y)>1)return;let hp={...g.hp},pos={...g.pos};if(x===g.pos[o].x&&y===g.pos[o].y){hp[o]--;if(hp[o]<=0)await save({state:{...g,hp,winner:m}});else await save({state:{...g,hp,turn:o}})}else{pos[m]={x,y};await save({state:{...g,pos,turn:o}})}}
async function shipShot(i){const g=state.state,m=me(state),o=other(m);if(g.winner||g.turn!==m||g.shots[m].includes(i))return;const shots={...g.shots,[m]:[...g.shots[m],i]},hits={...g.hits};if((g.ships[o]||[]).includes(i))hits[m]=[...(g.hits[m]||[]),i];let w=0;if(hits[m].length>=(g.ships[o]||[]).length)w=m;await save({state:{...g,shots,hits,winner:w,turn:w?m:o}})}
async function quiz(a){const g=state.state,m=me(state);if(g.answers[m]!=null||g.finished)return;const ans={...g.answers,[m]:a};if(ans[1]==null||ans[2]==null)return save({state:{...g,answers:ans}});const sc={...g.scores};if(ans[1]===Q[g.q][2])sc[1]++;if(ans[2]===Q[g.q][2])sc[2]++;const q=g.q+1,fin=q>=Q.length;await save({state:{...g,answers:{1:null,2:null},q, scores:sc,finished:fin,winner:fin?(sc[1]===sc[2]?-1:sc[1]>sc[2]?1:2):0}})}
async function raceMove(boost){const g=state.state,m=me(state);if(g.finished)return;let pos={...g.pos},boosts={...g.boost};if(boost&&boosts[m])return toast('Boost already used');let d=10+Math.floor(Math.random()*8);if(boost){d=25;boosts[m]=1}pos[m]=Math.min(100,pos[m]+d);const w=pos[m]>=100?m:0;await save({state:{...g,pos,boost:boosts,finished:!!w,winner:w}})}
async function archery(a){const g=state.state,m=me(state);if(g.shots[m]?.length>=g.round)return;const shots={...g.shots,[m]:[...(g.shots[m]||[]),a]};if((shots[1]||[]).length<g.round||(shots[2]||[]).length<g.round)return save({state:{...g,shots}});const wind=Math.floor(Math.random()*31)-15,score=x=>Math.max(0,100-Math.abs(x-(50+wind))*2),s={...g.score};const r1=score(shots[1].at(-1)),r2=score(shots[2].at(-1));if(r1>r2)s[1]++;else if(r2>r1)s[2]++;const round=g.round+1,fin=round>5;await save({state:{...g,shots,round,score:s,finished:fin,winner:fin?(s[1]===s[2]?-1:s[1]>s[2]?1:2):0}})}
async function bombMove(x,y){const g=state.state,m=me(state),o=other(m),p=g.players[m];if(g.winner||g.turn!==m||Math.abs(x-p.x)+Math.abs(y-p.y)>1)return;let ps=JSON.parse(JSON.stringify(g.players)),bombs=[...g.bombs];ps[m]={...ps[m],x,y};const bi=bombs.findIndex(b=>b.x===x&&b.y===y);if(bi>=0){ps[m].hp--;bombs.splice(bi,1)}else if(Math.random()<.25)bombs.push({x:p.x,y:p.y});let w=ps[m].hp<=0?o:0;await save({state:{...g,players:ps,bombs,turn:o,winner:w}})}
async function wordMove(v){v=v.trim().toUpperCase();const g=state.state,m=me(state);if(!/^[A-Z]+$/.test(v)||!v.startsWith(g.letter)||g.letters[m])return toast('Enter a valid word starting with the letter');const letters={...g.letters,[m]:v};if(!letters[1]||!letters[2])return save({state:{...g,letters}});const sc={...g.scores};sc[1]+=letters[1].length;sc[2]+=letters[2].length;const round=g.round+1,fin=round>5;await save({state:{...g,letters:{1:'',2:''},scores:sc,round,letter:String.fromCharCode(65+Math.floor(Math.random()*26)),finished:fin,winner:fin?(sc[1]===sc[2]?-1:sc[1]>sc[2]?1:2):0}})}
async function castleMove(a){const g=state.state,m=me(state),o=other(m);if(g.winner||g.turn!==m)return;let hp={...g.hp},r={...g.resources};if(a==='attack'&&r[m]>0){r[m]--;hp[o]=Math.max(0,hp[o]-2)}else if(a==='repair'&&r[m]>0){r[m]--;hp[m]=Math.min(10,hp[m]+1)}else if(a==='charge'){r[m]++}else return toast('Not enough resources');const w=hp[o]===0?m:0;await save({state:{...g,hp,resources:r,winner:w,turn:w?m:o}})}
async function numberMove(v){const g=state.state,m=me(state);if(g.finished||v<10||v>100||g.guesses[m].includes(v))return;const gs={...g.guesses,[m]:[...g.guesses[m],v]};if(v===g.secret)return save({state:{...g,guesses:gs,finished:true,winner:m,last:'Exact guess! 🎉'}});const last=v<g.secret?'Higher':'Lower';await save({state:{...g,guesses:gs,last:`${v}: ${last}`}})}
async function restart(){if(state)await save({state:fresh(state.game)})} async function leave(){if(roomId&&uid)try{await remove(ref(db,`rooms/${roomId}/players/${uid}`))}catch{}leaveLocal()}function leaveLocal(){if(roomUnsub)roomUnsub();roomUnsub=null;roomId=null;state=null;show('home')}
function renderGeneric(g,m){setBoard(`<div class="result"><h2>${games[g.game]?.[1]||'Game'}</h2><p>This game is ready for expansion.</p></div>`)}
$('createBtn').onclick=createRoom;$('joinBtn').onclick=joinRoom;$('copyBtn').onclick=async()=>{await navigator.clipboard.writeText(roomId);toast('Room code copied!')};$('leaveBtn').onclick=leave;$('gameLeaveBtn').onclick=leave;$('restartBtn').onclick=restart;$('roomInput').oninput=e=>e.target.value=e.target.value.toUpperCase();$('nameInput').addEventListener('keydown',e=>{if(e.key==='Enter')createRoom()});$('roomInput').addEventListener('keydown',e=>{if(e.key==='Enter')joinRoom()});initGrid();onAuthStateChanged(auth,u=>{
  uid=u?.uid||null;
  if(!uid){
    signInAnonymously(auth).catch(e=>{
      console.error('Firebase Auth error:',e);
      status('homeStatus','Firebase login failed. Enable Anonymous Authentication in Firebase Console.',true);
    });
  } else {
    status('homeStatus','Connected ✓');
  }
});
